### ISSUE TITLE
Won't build on Ubuntu 18.04 

### ISSUE THREAD

**Issue by rinarchy** [padloc/padloc#273]
Hey All,

Trying to build this on Ubuntu 18.04 and it just isn't working for me. Below is the logging output:

```
rin@poc-padloc:~/padloc$ npm run pwa:build

> padloc@3.0.10 pwa:build /home/rin/padloc
> lerna run build --scope @padloc/pwa

lerna notice cli v3.20.2
lerna notice filter including "@padloc/pwa"
lerna info filter [ '@padloc/pwa' ]
lerna info Executing command in 1 package: "npm run build"
lerna ERR! npm run build exited 2 in '@padloc/pwa'
lerna ERR! npm run build stdout:

> @padloc/pwa@3.0.14 build /home/rin/padloc/packages/pwa
> webpack

   374 modules

ERROR in /home/rin/padloc/packages/app/src/sw.ts
[tsl] ERROR in /home/rin/padloc/packages/app/src/sw.ts(3,15)
      TS2451: Cannot redeclare block-scoped variable 'workbox'.

ERROR in /home/rin/padloc/packages/app/src/sw.ts
[tsl] ERROR in /home/rin/padloc/packages/app/src/sw.ts(8,9)
      TS2339: Property 'routing' does not exist on type 'typeof import("/home/rin/padloc/packages/app/node_modules/@types/workbox-sw/index")'.

ERROR in /home/rin/padloc/packages/app/src/sw.ts
[tsl] ERROR in /home/rin/padloc/packages/app/src/sw.ts(8,49)
      TS2339: Property 'precaching' does not exist on type 'typeof import("/home/rin/padloc/packages/app/node_modules/@types/workbox-sw/index")'.

lerna ERR! npm run build stderr:
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @padloc/pwa@3.0.14 build: `webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @padloc/pwa@3.0.14 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rin/.npm/_logs/2020-04-06T15_48_24_784Z-debug.log

lerna ERR! npm run build exited 2 in '@padloc/pwa'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! padloc@3.0.10 pwa:build: `lerna run build --scope @padloc/pwa`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the padloc@3.0.10 pwa:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rin/.npm/_logs/2020-04-06T15_48_24_821Z-debug.log
rin@poc-padloc:~/padloc$
```

Any help would be appreciated so far this is the most promising piece of tech for what I'm trying to accomplish, thank you all for the help :)

Rin

**Comment by MaKleSoft** [comment]
Hm, strange. Looks like you might have the wrong version or `@types/workbox-sw`. Can you check which version you have installed? Your node and npm versions would be helpful to know, too.

```sh
npm -v
node -v
cd packages/app
npm list @types/workbox-sw
```

Also, please try the following

```sh
npm update
npm ci
```
and see if the problem persists.

**Comment by rinarchy** [comment]
@MaKleSoft thank you for this! I managed to get it working in the end, however, I have one issue right now where padloc will just show as "offline" when I browse to the pwa.

Looking into it right now but if you know any quick fixes for it?

**Comment by MaKleSoft** [comment]
Did you set the `PL_SERVER_URL` environment variable?

**Comment by rinarchy** [comment]
@MaKleSoft heya, I got all of this working now. I'm at the point where it's up and it's online, however, I'm now at the stage where this needs SSL.

I'm trying to use nginx to act as a reverse proxy but I'm struggling with some mixed content errors.

Do you have any documentation for the SSL setup for this? 

Thank you so much for your help so far!

**Comment by MaKleSoft** [comment]
You'll need a separate proxy pass to your backend (running on port 3000). I recommend setting up a separate subdomain for that. Here is how the config for the official pwa and server looks like:

```nginx
server {
    listen 443 ssl;
    server_name web.padloc.app;

    root /path/to/padloc/packages/pwa/build;
    index index.html;

    gzip on;
    gzip_types text/html text/css application/javascript;

    add_header X-Frame-Options deny;

    location / {
        try_files $uri /index.html;
    }

    ssl_certificate /etc/letsencrypt/live/padloc.app/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/padloc.app/privkey.pem; # managed by Certbot
}

server {
    listen 443 ssl http2;
    server_name api.padloc.app;

    location / {
        proxy_pass http://localhost:3000;
    }

    client_max_body_size 10M;

    ssl_certificate /etc/letsencrypt/live/padloc.app/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/padloc.app/privkey.pem; # managed by Certbot
}
```

Note that to reduce overhead we're using nginx to serve the pwa directly instead of using the node static server bundled with the repo. You can also proxy pass to 8080 if you prefer that. I also recommend using letsencrypt for your certificates instead of a self-signed one.

**Comment by rinarchy** [comment]
Thanks for this - The one thing that I am trying to do now is get a self signed cert to work. 

This isn't an external system or a system that will have internet access and will be running on our internal domain, with a self-signed cert, or a CA from our domain neither works both popping out different errors.

With the self signed it is "DEPTH_ZERO_SELF_SIGNED_CERT" - Is there anyway to get padloc to accept a self signed cert? If not, I'll make do, however, it'd make my life so much easier.

**Comment by MaKleSoft** [comment]
I'm afraid using self-signed certificate is not possible at this point. why not simply use letsencrypt?

**Comment by giansalex** [comment]
@rinarchy you can use certbot, https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx
